### ISSUE TITLE
Installation aborted even when passing checksum

### ISSUE THREAD

**Issue by jooize** [cmacrae/savemacos#17]
https://github.com/cmacrae/savemacos/commit/47c7f1d33fad763e717b35fc9bb98831801edcf9#diff-ca4c50b905dc21ea17a10549a6f5944fR111

`exit` always triggers and prevents installation even when checksumming succeeds.

**Comment by cmacrae** [comment]
Agh! Cheers for picking this up 🙄 I've simply reverted the attempted enhancement for now 👍
